version: 1
metadata_directory: metadata
endpoint: "{{ENV_LOCAL_HLAMBDA_ENDPOINT}}"
admin_secret: "{{ENV_LOCAL_HLAMBDA_ADMIN_SECRET}}"

# endpoint: "http://localhost:8081"
# admin_secret: demo

metadata_post_apply_script:
  - npm install --only=production

metadata_apply_ignore:
  - node_modules/
  - .git/
  - .vscode/
  - .DS_Store

# metadata_git_repository_sync_interval: ""
# metadata_git_repository: ""
# metadata_git_repository_access: ""

